Repository cyfronet-fid/recommender-system, pull requests merged in 2021-07, with the labels that each got.

#113 [#110, #68] Update endpoint, model reloading
  README.md
  recommender/api/__init__.py
  recommender/api/endpoints/reload.py
  recommender/api/endpoints/training.py
  recommender/api/endpoints/update.py
  recommender/engine/agents/pre_agent/pre_agent.py
  recommender/engine/agents/rl_agent/rl_agent.py
  recommender/tasks/neural_networks.py
  settings.py
Labels: API, enhancement

#117 [#114] Proper agents reloading
  README.md
  recommender/__init__.py
  recommender/api/__init__.py
  recommender/api/endpoints/recommendations.py
  recommender/api/endpoints/update.py
  recommender/engine/agents/rl_agent/training/common.py
  recommender/tasks/neural_networks.py
  tests/endpoints/test_training.py
  tests/tasks/test_training_task.py
  tests/test_pre_agent.py
Labels: bug, enhancement

#119 [#3] Configure Github Actions CI
  .github/workflows/python-app.yml
  .pylintrc
  Pipfile
  Pipfile.lock
  README.md
  recommender/api/endpoints/recommendations.py
  recommender/api/endpoints/reload.py
  recommender/engine/agents/pre_agent/datasets/all_datasets.py
  recommender/engine/agents/pre_agent/datasets/neural_collaborative_filtering.py
  recommender/engine/agents/pre_agent/pre_agent.py
  recommender/engine/agents/pre_agent/training/common.py
  recommender/engine/agents/rl_agent/preprocessing/reward_encoder.py
  recommender/engine/training/autoencoders.py
  tasks/rl_agent/fake_data_training.py
  tests/factories/state.py
  tests/test_critic_model.py
Labels: devops

#120 [#111] Smart Examples in Swagger
  recommender/api/schemas/recommendation.py
  recommender/utils.py
Labels: bug, enhancement

#122 [#121] Move _load_models() to init in agents classes
  recommender/engine/agents/base_agent.py
  recommender/engine/agents/pre_agent/pre_agent.py
  recommender/engine/agents/rl_agent/rl_agent.py
  tests/endpoints/test_recommendations.py
  tests/test_pre_agent.py
Labels: enhancement

#125 [#124] Refactoring
  recommender/engine/agents/pre_agent/training/common.py
  recommender/engine/agents/rl_agent/datasets/replay_buffer.py
  recommender/engine/agents/rl_agent/training/common.py
  recommender/engine/agents/rl_agent/utils.py
  recommender/services/sarses_generator.py
  tests/factories/search_data.py
  tests/test_replay_buffer.py
  tests/test_rl_agent.py
Labels: enhancement

#126 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
Labels: bug, enhancement

#128 [#127] Silence visit_id=None bug
  recommender/api/schemas/recommendation.py
  recommender/api/schemas/user_action.py
Labels: bug

#133 [HOTFIX] fix AGENT_VERSION default in execute_training task
  recommender/tasks/neural_networks.py
Labels: bug
