Repository cyfronet-fid/recommender-system, pull requests merged in 2021-05, with the labels that each got.

#52 RL agent architecture
  recommender/engine/base_agent_recommender.py
  recommender/engine/pre_agent/models/autoencoders.py
  recommender/engine/rl_agent/__init__.py
  recommender/engine/rl_agent/action_selector.py
  recommender/engine/rl_agent/architecture_and_interfaces.py
  recommender/engine/rl_agent/datasets/__init__.py
  recommender/engine/rl_agent/datasets/replay_buffer_generator.py
  recommender/engine/rl_agent/models/__init__.py
  recommender/engine/rl_agent/models/actor_model.py
  recommender/engine/rl_agent/models/critic_model.py
  recommender/engine/rl_agent/models/history_embedder.py
  recommender/engine/rl_agent/preprocessing/__init__.py
  recommender/engine/rl_agent/preprocessing/action_embedder.py
  recommender/engine/rl_agent/preprocessing/filters_embedder.py
  recommender/engine/rl_agent/preprocessing/searchphrase_embedder.py
  recommender/engine/rl_agent/preprocessing/state_embedder.py
  recommender/engine/rl_agent/rl_agent.py
  recommender/engine/rl_agent/training/__init__.py
  recommender/engine/rl_agent/training/common.py
Labels: ML, enhancement

#70 [#54] Filters Embedder
  recommender/engine/rl_agent/preprocessing/filters_embedder.py
Labels: ML, enhancement

#72 [#55] Search phrase Embedder
  Pipfile
  Pipfile.lock
  recommender/engine/rl_agent/preprocessing/searchphrase_embedder.py
Labels: ML, enhancement

#74 [#53] State Embedder
  Pipfile
  Pipfile.lock
  recommender/engine/rl_agent/preprocessing/filters_embedder.py
  recommender/engine/rl_agent/preprocessing/searchphrase_embedder.py
  recommender/engine/rl_agent/preprocessing/state_embedder.py
  recommender/models/sars.py
  recommender/models/state.py
  recommender/services/sarses_generator.py
  tests/factories/search_data.py
  tests/factories/state.py
  tests/test_embedders.py
Labels: ML, enhancement

#51 [#1998] Don't recommend unpublished services
  recommender/api/endpoints/recommendations.py
  recommender/engine/pre_agent/pre_agent.py
  recommender/errors.py
  recommender/models/service.py
  recommender/services/fts.py
  tests/factories/marketplace/service.py
  tests/test_pre_agent.py
Labels: bug, enhancement

#80 [#73] Services History Generator
  Pipfile
  recommender/services/sarses_generator.py
  recommender/services/services_history_generator.py
  recommender/utils.py
  tests/services/test_services_history_generator.py
Labels: ML, bug, enhancement

#78 [#60] Base Agent Recommender
  recommender/engine/base_agent_recommender.py
  recommender/engine/pre_agent/pre_agent.py
  tests/test_pre_agent.py
Labels: ML, enhancement

#77 [#56] Actor
  recommender/engine/rl_agent/models/actor_model.py
  recommender/engine/rl_agent/models/history_model.py
  recommender/engine/rl_agent/models/lstm_model.py
  recommender/engine/rl_agent/models/search_phrase_model.py
  tests/test_actor_model.py
  tests/test_history_embedder.py
  tests/test_history_model.py
  tests/test_lstm_model.py
  tests/test_search_phrase_model.py
Labels: Epic

#97 [#96] fill_candidate_services bugs
  recommender/api/endpoints/recommendations.py
  recommender/engine/base_agent_recommender.py
  recommender/engine/pre_agent/pre_agent.py
  recommender/services/fts.py
  tests/test_pre_agent.py
Labels: bug

#105 [#89, #90] Action Encoder, Action Embedder and Critic
  recommender/engine/agents/rl_agent/models/action_embedder.py
  recommender/engine/agents/rl_agent/models/actor.py
  recommender/engine/agents/rl_agent/models/critic.py
  recommender/engine/agents/rl_agent/preprocessing/action_encoder.py
  tests/test_action_encoder.py
  tests/test_critic_model.py
  tests/test_embedders.py
Labels: ML, enhancement

#106 [#91] Replay Buffer
  recommender/engine/agents/rl_agent/datasets/replay_buffer.py
  recommender/engine/agents/rl_agent/datasets/replay_buffer_generator.py
  recommender/engine/agents/rl_agent/models/action_embedder.py
  recommender/engine/agents/rl_agent/preprocessing/action_encoder.py
  recommender/engine/agents/rl_agent/preprocessing/reward_encoder.py
  recommender/engine/agents/rl_agent/preprocessing/sars_encoder.py
  recommender/engine/agents/rl_agent/preprocessing/state_encoder.py
  tests/factories/sars.py
  tests/test_embedders.py
  tests/test_replay_buffer.py
  tests/test_reward_encoder.py
  tests/test_sars_encoder.py
Labels: ML, enhancement
