Repository cyfronet-fid/recommender-system, pull requests merged in 2021-03, with the labels that each got.

#22 [HOTFIX] pre-agent-hotfix
  Pipfile
  Pipfile.lock
  recommender/__init__.py
  training_and_inferention_example.ipynb
Labels: bug

#20 [HOTFIX] Mock celery tasks
  Pipfile
  Pipfile.lock
  recommender/__init__.py
  tests/endpoints/test_database_dumps.py
  tests/tasks/__init__.py
  tests/tasks/test_db.py
Labels: bug, enhancement

#24 [#23] Probes integration
  recommender/api/schemas/database_dump/service.py
  recommender/api/schemas/recommendation.py
  recommender/api/schemas/user_action.py
  recommender/engine/panel_id_to_services_number_mapping.py
  recommender/engine/pre_agent/pre_agent.py
  recommender/engine/recommender_engine_stub.py
  recommender/models/__init__.py
  recommender/models/recommendation.py
  recommender/models/search_data.py
  recommender/models/service.py
  recommender/models/state.py
  recommender/services/deserializer.py
  recommender/services/sarses_generator.py
  tests/conftest.py
  tests/factories/recommendation.py
  tests/services/test_sarses_generator.py
Labels: bug

#27 [HOTFIX] Fix tests
  recommender/engine/pre_agent/pre_agent.py
  tests/factories/recommendation.py
Labels: bug

#38 [#34] add sentry integration
  Pipfile
  Pipfile.lock
  README.md
  development.yml
  docker-compose.testing.yml
  production.yml
  recommender/__init__.py
  recommender/tasks/neural_networks.py
  worker.py
Labels: enhancement

#44 [#43] Remove logged_user field
  recommender/api/schemas/recommendation.py
  recommender/api/schemas/user_action.py
  recommender/engine/pre_agent/pre_agent.py
  recommender/models/recommendation.py
  recommender/models/user_action.py
  recommender/services/deserializer.py
  recommender/services/sarses_generator.py
  tests/factories/recommendation.py
  tests/factories/user_action/user_action.py
  tests/services/test_sarses_generator.py
  training_and_inferention_example.ipynb
Labels: enhancement

#40 [#28] full tests coverage
  Pipfile
  Pipfile.lock
  recommender/api/endpoints/recommendations.py
  recommender/api/schemas/user_action.py
  recommender/engine/pre_agent/datasets/common.py
  recommender/engine/pre_agent/models/common.py
  recommender/engine/pre_agent/pre_agent.py
  recommender/engine/pre_agent/preprocessing/preprocessing.py
  recommender/engine/pre_agent/preprocessing/transformers.py
  recommender/engine/recommender_engine_stub.py
  tests/conftest.py
  tests/endpoints/test_database_dumps.py
  tests/endpoints/test_recommendations.py
  tests/endpoints/test_training.py
  tests/endpoints/test_user_actions.py
  tests/services/test_deserializer.py
  tests/services/test_sarses_generator.py
  tests/tasks/test_preprocessing_task.py
  tests/tasks/test_training_task.py
  tests/test_neural_colaborative_filtering.py
  tests/test_nn_models.py
  tests/test_pre_agent.py
  tests/test_pre_agent_dataset.py
  tests/test_preprocessing.py
  tests/test_transformers.py
  training_and_inferention_example.ipynb
Labels: tests

#46 [HOTFIX] remove logged_user from tests and fixtures
  tests/conftest.py
  tests/endpoints/test_recommendations.py
  tests/endpoints/test_user_actions.py
  tests/services/test_deserializer.py
  tests/services/test_sarses_generator.py
  tests/test_pre_agent.py
Labels: bug
