Repository cyfronet-fid/recommender-system, pull requests merged in 2022-01, with the labels that each got.

#299 [#298] Fix: flask db seed command
  CHANGELOG.md
  recommender/commands/db.py
  recommender/errors.py
  tests/factories/populate_database.py
Labels: bug

#296 [#295] Enhance the language of the README
  README.md
Labels: documentation

#293 [#289] Using flask seed_faker command on an empty database
  CHANGELOG.md
  recommender/errors.py
  tests/factories/marketplace/faker_seeds/utils/dumpers.py
Labels: bug

#291 [#218] Create and configure log files
  CHANGELOG.md
  Pipfile
  Pipfile.lock
  README.md
  definitions.py
  logger_config.py
  recommender/__init__.py
  recommender/api/endpoints/recommendations.py
  recommender/engines/autoencoders/inference/embedding_component.py
  recommender/engines/autoencoders/ml_components/embedder.py
  recommender/engines/autoencoders/ml_components/normalizer.py
  recommender/engines/autoencoders/training/data_preparation_step.py
  recommender/engines/autoencoders/training/data_validation_step.py
  recommender/engines/autoencoders/training/model_training_step.py
  recommender/engines/autoencoders/training/model_validation_step.py
  recommender/engines/base/base_inference_component.py
  recommender/engines/base/base_pipeline.py
  recommender/engines/ncf/inference/ncf_inference_component.py
  recommender/engines/ncf/training/data_validation_step.py
  recommender/engines/ncf/training/model_validation_step.py
  recommender/engines/persistent_mixin.py
  recommender/engines/rl/ml_components/service_selector.py
  recommender/engines/rl/ml_components/synthetic_dataset/users.py
  recommender/engines/rl/training/data_validation_step/data_validation_step.py
  recommender/engines/rl/training/model_validation_step/model_validation_step.py
  recommender/migrate/base_migration.py
  recommender/migrate/utils.py
  recommender/tasks.py
  recommender/utils.py
  tensorboard_script.py
  tests/factories/marketplace/faker_seeds/utils/loaders.py
Labels: enhancement, refactor, concept work

#290 [#282] SARSes regeneration
  .github/workflows/python-app.yml
  .run/Flask (app.py).run.xml
  .run/celery worker.run.xml
  .run/coverage run --source=. -m pytest ..run.xml
  .run/hyperparameters_tuning.run.xml
  .run/pytest in tests 10 CPUs.run.xml
  .run/pytest in tests.run.xml
  .run/simulation.run.xml
  .run/tensorboard.run.xml
  CHANGELOG.md
  recommender/__init__.py
  recommender/commands/db.py
  recommender/engines/autoencoders/training/data_preparation_step.py
  recommender/engines/ncf/inference/ncf_inference_component.py
  recommender/engines/ncf/training/data_preparation_step.py
  recommender/engines/rl/ml_components/reward_encoder.py
  recommender/engines/rl/ml_components/sarses_generator.py
  recommender/engines/rl/training/data_extraction_step/data_extraction_step.py
  recommender/engines/rl/utils.py
  recommender/models/recommendation.py
  recommender/models/sars.py
  recommender/models/user.py
  recommender/models/user_action.py
  recommender/utils.py
  tests/conftest.py
  tests/migrate/test_base_migration.py
  tests/services/test_sarses_generator.py
  tests/services/user_journey.py
Labels: bug

#311 [#310] Fix: AE data preparation step - create_details - returns incorrect data
  CHANGELOG.md
  recommender/engines/autoencoders/training/data_preparation_step.py
  tests/unit/engines/autoencoders/training/test_data_preparation_step.py
Labels: bug

#319 [#312] Changes in the deletion of past SARS in the RL data extraction step
  CHANGELOG.md
  recommender/commands/db.py
  recommender/engines/rl/ml_components/sarses_generator.py
  recommender/engines/rl/ml_components/services_history_generator.py
  recommender/engines/rl/ml_components/synthetic_dataset/dataset.py
  recommender/engines/rl/training/data_extraction_step/data_extraction_step.py
Labels: bug

#322 [#317] Fix: trying to dereference unknown ID of a user (-1)
  CHANGELOG.md
  recommender/engines/base/persistent.py
  recommender/engines/rl/ml_components/sarses_generator.py
  recommender/engines/rl/training/data_extraction_step/data_extraction_step.py
Labels: bug

#313 [#314] fix multiprocessing in celery
  CHANGELOG.md
  recommender/engines/rl/ml_components/sarses_generator.py
  recommender/engines/rl/training/data_extraction_step/data_extraction_step.py
  recommender/tasks.py
  tests/conftest.py
  tests/services/test_sarses_generator.py
Labels: bug
